const stopWords = [
  'i',
  'me',
  'my',
  'myself',
  'we',
  'our',
  'ours',
  'ourselves',
  'you',
  'your',
  'yours',
  'yourself',
  'yourselves',
  'he',
  'him',
  'his',
  'himself',
  'she',
  'her',
  'hers',
  'herself',
  'it',
  'its',
  'itself',
  'they',
  'them',
  'their',
  'theirs',
  'themselves',
  'what',
  'which',
  'who',
  'whom',
  'this',
  'that',
  'these',
  'those',
  'am',
  'is',
  'are',
  'was',
  'were',
  'be',
  'been',
  'being',
  'have',
  'has',
  'had',
  'having',
  'do',
  'does',
  'did',
  'doing',
  'a',
  'an',
  'the',
  'and',
  'but',
  'if',
  'or',
  'because',
  'as',
  'until',
  'while',
  'of',
  'at',
  'by',
  'for',
  'with',
  'about',
  'against',
  'between',
  'into',
  'through',
  'during',
  'before',
  'after',
  'above',
  'below',
  'to',
  'from',
  'up',
  'down',
  'in',
  'out',
  'on',
  'off',
  'over',
  'under',
  'again',
  'further',
  'then',
  'once',
  'here',
  'there',
  'when',
  'where',
  'why',
  'how',
  'all',
  'any',
  'both',
  'each',
  'few',
  'more',
  'most',
  'other',
  'some',
  'such',
  'no',
  'nor',
  'not',
  'only',
  'own',
  'same',
  'so',
  'than',
  'too',
  'very',
  's',
  't',
  'can',
  'will',
  'just',
  'don',
  'should',
  'now',
];

export default stopWords;

export const spells = [
  'Acid Arrow',
  'Acid Splash',
  'Aid',
  'Alarm',
  'Alter Self',
  'Animal Friendship',
  'Animal Messenger',
  'Animal Shapes',
  'Animate Dead',
  'Animate Objects',
  'Antilife Shell',
  'Antimagic Field',
  'Antipathy/Sympathy',
  'Arcane Eye',
  'Arcane Hand',
  'Arcane Lock',
  'Arcane Sword',
  "Arcanist's Magic Aura",
  'Astral Projection',
  'Augury',
  'Awaken',
  'Bane',
  'Banishment',
  'Barkskin',
  'Beacon of Hope',
  'Bestow Curse',
  'Black Tentacles',
  'Blade Barrier',
  'Bless',
  'Blight',
  'Blindness/Deafness',
  'Blink',
  'Blur',
  'Branding Smite',
  'Burning Hands',
  'Call Lightning',
  'Calm Emotions',
  'Chain Lightning',
  'Charm Person',
  'Chill Touch',
  'Circle of Death',
  'Clairvoyance',
  'Clone',
  'Cloudkill',
  'Color Spray',
  'Command',
  'Commune',
  'Commune with Nature',
  'Comprehend Languages',
  'Compulsion',
  'Cone of Cold',
  'Confusion',
  'Conjure Animals',
  'Conjure Celestial',
  'Conjure Elemental',
  'Conjure Fey',
  'Conjure Minor Elementals',
  'Conjure Woodland Beings',
  'Contact Other Plane',
  'Contagion',
  'Contingency',
  'Continual Flame',
  'Control Water',
  'Control Weather',
  'Counterspell',
  'Create Food and Water',
  'Create Undead',
  'Create or Destroy Water',
  'Creation',
  'Cure Wounds',
  'Dancing Lights',
  'Darkness',
  'Darkvision',
  'Daylight',
  'Death Ward',
  'Delayed Blast Fireball',
  'Demiplane',
  'Detect Evil and Good',
  'Detect Magic',
  'Detect Poison and Disease',
  'Detect Thoughts',
  'Dimension Door',
  'Disguise Self',
  'Disintegrate',
  'Dispel Evil and Good',
  'Dispel Magic',
  'Divination',
  'Divine Favor',
  'Divine Word',
  'Dominate Beast',
  'Dominate Monster',
  'Dominate Person',
  'Dream',
  'Druidcraft',
  'Earthquake',
  'Eldritch Blast',
  'Enhance Ability',
  'Enlarge/Reduce',
  'Entangle',
  'Enthrall',
  'Etherealness',
  'Expeditious Retreat',
  'Eyebite',
  'Fabricate',
  'Faerie Fire',
  'Faithful Hound',
  'False Life',
  'Fear',
  'Feather Fall',
  'Feeblemind',
  'Find Familiar',
  'Find Steed',
  'Find Traps',
  'Find the Path',
  'Finger of Death',
  'Fire Bolt',
  'Fire Shield',
  'Fire Storm',
  'Fireball',
  'Flame Blade',
  'Flame Strike',
  'Flaming Sphere',
  'Flesh to Stone',
  'Floating Disk',
  'Fly',
  'Fog Cloud',
  'Forbiddance',
  'Forcecage',
  'Foresight',
  'Freedom of Movement',
  'Freezing Sphere',
  'Gaseous Form',
  'Gate',
  'Geas',
  'Gentle Repose',
  'Giant Insect',
  'Glibness',
  'Globe of Invulnerability',
  'Glyph of Warding',
  'Goodberry',
  'Grease',
  'Greater Invisibility',
  'Greater Restoration',
  'Guardian of Faith',
  'Guards and Wards',
  'Guidance',
  'Guiding Bolt',
  'Gust of Wind',
  'Hallow',
  'Hallucinatory Terrain',
  'Harm',
  'Haste',
  'Heal',
  'Healing Word',
  'Heat Metal',
  'Hellish Rebuke',
  "Heroes' Feast",
  'Heroism',
  'Hideous Laughter',
  'Hold Monster',
  'Hold Person',
  'Holy Aura',
  "Hunter's Mark",
  'Hypnotic Pattern',
  'Ice Storm',
  'Identify',
  'Illusory Script',
  'Imprisonment',
  'Incendiary Cloud',
  'Inflict Wounds',
  'Insect Plague',
  'Instant Summons',
  'Invisibility',
  'Irresistible Dance',
  'Jump',
  'Knock',
  'Legend Lore',
  'Lesser Restoration',
  'Levitate',
  'Light',
  'Lightning Bolt',
  'Locate Animals or Plants',
  'Locate Creature',
  'Locate Object',
  'Longstrider',
  'Mage Armor',
  'Mage Hand',
  'Magic Circle',
  'Magic Jar',
  'Magic Missile',
  'Magic Mouth',
  'Magic Weapon',
  'Magnificent Mansion',
  'Major Image',
  'Mass Cure Wounds',
  'Mass Heal',
  'Mass Healing Word',
  'Mass Suggestion',
  'Maze',
  'Meld into Stone',
  'Mending',
  'Message',
  'Meteor Swarm',
  'Mind Blank',
  'Minor Illusion',
  'Mirage Arcane',
  'Mirror Image',
  'Mislead',
  'Misty Step',
  'Modify Memory',
  'Moonbeam',
  'Move Earth',
  'Nondetection',
  'Pass without Trace',
  'Passwall',
  'Phantasmal Killer',
  'Phantom Steed',
  'Planar Ally',
  'Planar Binding',
  'Plane Shift',
  'Plant Growth',
  'Poison Spray',
  'Polymorph',
  'Power Word Kill',
  'Power Word Stun',
  'Prayer of Healing',
  'Prestidigitation',
  'Prismatic Spray',
  'Prismatic Wall',
  'Private Sanctum',
  'Produce Flame',
  'Programmed Illusion',
  'Project Image',
  'Protection from Energy',
  'Protection from Evil and Good',
  'Protection from Poison',
  'Purify Food and Drink',
  'Raise Dead',
  'Ray of Enfeeblement',
  'Ray of Frost',
  'Regenerate',
  'Reincarnate',
  'Remove Curse',
  'Resilient Sphere',
  'Resistance',
  'Resurrection',
  'Reverse Gravity',
  'Revivify',
  'Rope Trick',
  'Sacred Flame',
  'Sanctuary',
  'Scorching Ray',
  'Scrying',
  'Secret Chest',
  'See Invisibility',
  'Seeming',
  'Sending',
  'Sequester',
  'Shapechange',
  'Shatter',
  'Shield',
  'Shield of Faith',
  'Shillelagh',
  'Shocking Grasp',
  'Silence',
  'Silent Image',
  'Simulacrum',
  'Sleep',
  'Sleet Storm',
  'Slow',
  'Spare the Dying',
  'Speak with Animals',
  'Speak with Dead',
  'Speak with Plants',
  'Spider Climb',
  'Spike Growth',
  'Spirit Guardians',
  'Spiritual Weapon',
  'Stinking Cloud',
  'Stone Shape',
  'Stoneskin',
  'Storm of Vengeance',
  'Suggestion',
  'Sunbeam',
  'Sunburst',
  'Symbol',
  'Telekinesis',
  'Telepathic Bond',
  'Teleport',
  'Teleportation Circle',
  'Thaumaturgy',
  'Thunderwave',
  'Time Stop',
  'Tiny Hut',
  'Tongues',
  'Transport via Plants',
  'Tree Stride',
  'True Polymorph',
  'True Resurrection',
  'True Seeing',
  'True Strike',
  'Unseen Servant',
  'Vampiric Touch',
  'Vicious Mockery',
  'Wall of Fire',
  'Wall of Force',
  'Wall of Ice',
  'Wall of Stone',
  'Wall of Thorns',
  'Warding Bond',
  'Water Breathing',
  'Water Walk',
  'Web',
  'Weird',
  'Wind Walk',
  'Wind Wall',
  'Wish',
  'Word of Recall',
  'Zone of Truth',
];

export const monsters = [
  'Aboleth',
  'Acolyte',
  'Adult Black Dragon',
  'Adult Blue Dragon',
  'Adult Brass Dragon',
  'Adult Bronze Dragon',
  'Adult Copper Dragon',
  'Adult Gold Dragon',
  'Adult Green Dragon',
  'Adult Red Dragon',
  'Adult Silver Dragon',
  'Adult White Dragon',
  'Air Elemental',
  'Ancient Black Dragon',
  'Ancient Blue Dragon',
  'Ancient Brass Dragon',
  'Ancient Bronze Dragon',
  'Ancient Copper Dragon',
  'Ancient Gold Dragon',
  'Ancient Green Dragon',
  'Ancient Red Dragon',
  'Ancient Silver Dragon',
  'Ancient White Dragon',
  'Androsphinx',
  'Animated Armor',
  'Ankheg',
  'Ape',
  'Archmage',
  'Assassin',
  'Awakened Shrub',
  'Awakened Tree',
  'Axe Beak',
  'Azer',
  'Baboon',
  'Badger',
  'Balor',
  'Bandit',
  'Bandit Captain',
  'Barbed Devil',
  'Basilisk',
  'Bat',
  'Bearded Devil',
  'Behir',
  'Berserker',
  'Black Dragon Wyrmling',
  'Black Pudding',
  'Black bear',
  'Blink Dog',
  'Blood Hawk',
  'Blue Dragon Wyrmling',
  'Boar',
  'Bone Devil',
  'Brass Dragon Wyrmling',
  'Bronze Dragon Wyrmling',
  'Brown Bear',
  'Bugbear',
  'Bulette',
  'Camel',
  'Cat',
  'Centaur',
  'Chain Devil',
  'Chimera',
  'Chuul',
  'Clay Golem',
  'Cloaker',
  'Cloud Giant',
  'Cockatrice',
  'Commoner',
  'Constrictor Snake',
  'Copper Dragon Wyrmling',
  'Couatl',
  'Crab',
  'Crocodile',
  'Cult Fanatic',
  'Cultist',
  'Darkmantle',
  'Death Dog',
  'Deer',
  'Deva',
  'Dire Wolf',
  'Djinni',
  'Doppelganger',
  'Draft Horse',
  'Dragon Turtle',
  'Dretch',
  'Drider',
  'Druid',
  'Dryad',
  'Duergar',
  'Dust Mephit',
  'Eagle',
  'Earth Elemental',
  'Efreeti',
  'Elephant',
  'Elf, Drow',
  'Elk',
  'Erinyes',
  'Ettercap',
  'Ettin',
  'Fire Elemental',
  'Fire Giant',
  'Flesh Golem',
  'Flying Snake',
  'Flying Sword',
  'Frog',
  'Frost Giant',
  'Gargoyle',
  'Gelatinous Cube',
  'Ghast',
  'Ghost',
  'Ghoul',
  'Giant Ape',
  'Giant Badger',
  'Giant Bat',
  'Giant Boar',
  'Giant Centipede',
  'Giant Constrictor Snake',
  'Giant Crab',
  'Giant Crocodile',
  'Giant Eagle',
  'Giant Elk',
  'Giant Fire Beetle',
  'Giant Frog',
  'Giant Goat',
  'Giant Hyena',
  'Giant Lizard',
  'Giant Octopus',
  'Giant Owl',
  'Giant Poisonous Snake',
  'Giant Rat',
  'Giant Scorpion',
  'Giant Sea Horse',
  'Giant Shark',
  'Giant Spider',
  'Giant Toad',
  'Giant Vulture',
  'Giant Wasp',
  'Giant Weasel',
  'Giant Wolf Spider',
  'Gibbering Mouther',
  'Glabrezu',
  'Gladiator',
  'Gnoll',
  'Goat',
  'Goblin',
  'Gold Dragon Wyrmling',
  'Gorgon',
  'Gray Ooze',
  'Green Dragon Wyrmling',
  'Green Hag',
  'Grick',
  'Griffon',
  'Grimlock',
  'Guard',
  'Guardian Naga',
  'Gynosphinx',
  'Half-Red Dragon Veteran',
  'Harpy',
  'Hawk',
  'Hell Hound',
  'Hezrou',
  'Hill Giant',
  'Hippogriff',
  'Hobgoblin',
  'Homunculus',
  'Horned Devil',
  'Hunter Shark',
  'Hydra',
  'Hyena',
  'Ice Devil',
  'Ice Mephit',
  'Imp',
  'Invisible Stalker',
  'Iron Golem',
  'Jackal',
  'Killer Whale',
  'Knight',
  'Kobold',
  'Kraken',
  'Lamia',
  'Lemure',
  'Lich',
  'Lion',
  'Lizard',
  'Lizardfolk',
  'Mage',
  'Magma Mephit',
  'Magmin',
  'Mammoth',
  'Manticore',
  'Marilith',
  'Mastiff',
  'Medusa',
  'Merfolk',
  'Merrow',
  'Mimic',
  'Minotaur',
  'Minotaur Skeleton',
  'Mule',
  'Mummy',
  'Mummy Lord',
  'Nalfeshnee',
  'Night Hag',
  'Nightmare',
  'Noble',
  'Ochre Jelly',
  'Octopus',
  'Ogre',
  'Ogre Zombie',
  'Oni',
  'Orc',
  'Otyugh',
  'Owl',
  'Owlbear',
  'Panther',
  'Pegasus',
  'Phase Spider',
  'Pit Fiend',
  'Planetar',
  'Plesiosaurus',
  'Poisonous Snake',
  'Polar Bear',
  'Pony',
  'Priest',
  'Pseudodragon',
  'Purple Worm',
  'Quasit',
  'Quipper',
  'Rakshasa',
  'Rat',
  'Raven',
  'Red Dragon Wyrmling',
  'Reef Shark',
  'Remorhaz',
  'Rhinoceros',
  'Riding Horse',
  'Roc',
  'Roper',
  'Rug of Smothering',
  'Rust Monster',
  'Saber-Toothed Tiger',
  'Sahuagin',
  'Salamander',
  'Satyr',
  'Scorpion',
  'Scout',
  'Sea Hag',
  'Sea Horse',
  'Shadow',
  'Shambling Mound',
  'Shield Guardian',
  'Shrieker',
  'Silver Dragon Wyrmling',
  'Skeleton',
  'Solar',
  'Specter',
  'Spider',
  'Spirit Naga',
  'Sprite',
  'Spy',
  'Steam Mephit',
  'Stirge',
  'Stone Giant',
  'Stone Golem',
  'Storm Giant',
  'Succubus/Incubus',
  'Swarm of Bats',
  'Swarm of Insects',
  'Swarm of Poisonous Snakes',
  'Swarm of Quippers',
  'Swarm of Rats',
  'Swarm of Ravens',
  'Tarrasque',
  'Thug',
  'Tiger',
  'Treant',
  'Tribal Warrior',
  'Triceratops',
  'Troll',
  'Tyrannosaurus Rex',
  'Unicorn',
  'Vampire',
  'Vampire Spawn',
  'Veteran',
  'Violet Fungus',
  'Vrock',
  'Vulture',
  'Warhorse',
  'Warhorse Skeleton',
  'Water Elemental',
  'Weasel',
  'Werebear',
  'Wereboar',
  'Wererat',
  'Weretiger',
  'Werewolf',
  'White Dragon Wyrmling',
  'Wight',
  "Will-o'-Wisp",
  'Winter Wolf',
  'Wolf',
  'Worg',
  'Wraith',
  'Wyvern',
  'Xorn',
  'Young Black Dragon',
  'Young Blue Dragon',
  'Young Brass Dragon',
  'Young Bronze Dragon',
  'Young Copper Dragon',
  'Young Gold Dragon',
  'Young Green Dragon',
  'Young Red Dragon',
  'Young Silver Dragon',
  'Young White Dragon',
  'Zombie',
];
